name: SonarCloud Scan
description: >
  Scan your code with SonarCloud to detect bugs, vulnerabilities and code smells
  in 26+ programming languages.
branding:
  icon: check
  color: green
runs:
  using: docker
  image: Dockerfile
  entrypoint: "/entrypoint.sh"
  post-entrypoint: "/cleanup.sh"
inputs:
  token:
    description: SonarCloud token
    require: true
#  github-token:
#    description: Github token for build
#    require: true
  args:
    description: Additional arguments to the sonarcloud scanner
    required: false
  project-base-dir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
    default: .
